### ISSUE TITLE
brain_images folder

### ISSUE THREAD

**Issue by ctpn** [broadinstitute/one-shot-atlas#1]
Hello. Great paper! Thank you for making the code public.
I would like to run Predictions.ipynb but cannot find the images for the brain_images folder.

> You will also need to populate the brain_images folder with the mouse brain samples that can be found at: LINK
seems to have no link.

Thank you for your time.

**Comment by Buffoni** [comment]
In order to run Predictions.ipynb you need to populate the brain_images folder following the structure detailed in the respective README file inside.
Working links to access all the datasets used for both testing and training can be found in the "Methods" section of our paper (linked in the README) under the subsection "Image datasets for registration pipeline".
Thank you for your interest in the paper!
